apiVersion: v1
kind: Service
metadata:
  name: {{ include "ranks.fullname" . }}-api
  labels:
    {{- include "ranks.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "ranks.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.ranks.api.service.port }}
      targetPort: http
