apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ranks.fullname" . }}-db
  labels:
    {{- include "ranks.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.ranks.database.host | quote }}
  port: {{ .Values.ranks.database.port | quote }}
  dbname: {{ .Values.ranks.database.name | quote }}
  user: {{ .Values.ranks.database.user | quote }}
  password: {{ .Values.ranks.database.password | quote }}
