apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ranks.fullname" . }}-web
  labels:
    {{- include "ranks.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.ranks.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ranks.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "ranks.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.ranks.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.ranks.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.ranks.web.image.repository }}:{{ .Values.ranks.web.image.tag }}"
          imagePullPolicy: {{ .Values.ranks.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ranks.web.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
          {{- with .Values.ranks.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
